name: Laravel CI - Merge Gate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: laravel_nutrition_test
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: user_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, redis
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Copy environment file
      run: cp docker-env-example.txt .env

    - name: Install PHP dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Install Node dependencies
      run: npm ci

    - name: Generate application key
      run: php artisan key:generate

    - name: Create database
      run: |
        mysql -h 127.0.0.1 -u laravel_user -puser_password -e "CREATE DATABASE IF NOT EXISTS laravel_nutrition_test;"

    - name: Run database migrations
      run: php artisan migrate --env=testing

    - name: Run database seeders
      run: php artisan db:seed --class=CypressTestSeeder --env=testing

    - name: Run PHPUnit tests
      run: php artisan test --env=testing
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_nutrition_test
        DB_USERNAME: laravel_user
        DB_PASSWORD: user_password
        CACHE_DRIVER: redis
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Build frontend assets
      run: npm run build

    - name: Test application startup
      run: |
        php artisan serve --host=0.0.0.0 --port=8000 &
        sleep 10
        curl -f http://localhost:8000 || exit 1
        pkill -f "php artisan serve"

  cypress:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    needs: test
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: laravel_nutrition_test
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: user_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, redis

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Copy environment file
      run: cp docker-env-example.txt .env

    - name: Install PHP dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Install Node dependencies
      run: npm ci

    - name: Generate application key
      run: php artisan key:generate

    - name: Create database
      run: |
        mysql -h 127.0.0.1 -u laravel_user -puser_password -e "CREATE DATABASE IF NOT EXISTS laravel_nutrition_test;"

    - name: Run database migrations
      run: php artisan migrate --env=testing

    - name: Run database seeders
      run: php artisan db:seed --class=CypressTestSeeder --env=testing

    - name: Build frontend assets
      run: npm run build

    - name: Start Laravel server
      run: |
        php artisan serve --host=0.0.0.0 --port=8000 &
        sleep 5

    - name: Run Cypress tests
      run: npm run cypress:run
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel_nutrition_test
        DB_USERNAME: laravel_user
        DB_PASSWORD: user_password
        CACHE_DRIVER: redis
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: 6379
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Upload Cypress screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Upload Cypress videos
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos

  security:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install PHP dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run security audit
      run: composer audit

    - name: Run PHP CS Fixer
      run: ./vendor/bin/pint --test

  docker-compose:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start services with docker-compose
      run: |
        docker compose up -d
        sleep 30

    - name: Wait for services to be ready
      run: |
        docker compose exec -T app php artisan migrate --force
        docker compose exec -T app php artisan db:seed --class=CypressTestSeeder --force

    - name: Test application with docker-compose
      run: |
        curl -f http://localhost:8001 || exit 1
        echo "✅ Application is running with docker-compose!"

    - name: Run tests with docker-compose
      run: |
        docker compose exec -T app php artisan test
        echo "✅ Tests passed with docker-compose!"

    - name: Stop services
      if: always()
      run: docker compose down
