name: Laravel CI - MVP

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual runs

jobs:
  test:
    name: Laravel Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, dom, fileinfo


    - name: Copy environment file
      run: cp docker-env-example.txt .env

    - name: Install PHP dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Generate application key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"



